{% set name = "ghstack" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ghstack-{{ version }}.tar.gz
  sha256: 1f44f4dea6a733d050ef6c062330665c00e4bceafcb9fb8aee6c49d67d458aec

build:
  entry_points:
    - ghstack = ghstack.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3,<4
    - click >=8,<9
    - requests >=2,<3
    - typing-extensions >=3,<5
    - flake8 >=7,<8

test:
  imports:
    - ghstack
  commands:
    - pip check
    - ghstack --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ezyang/ghstack
  summary: Stack diff support for GitHub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
