{% set name = "ghstack" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ghstack-{{ version }}.tar.gz
  sha256: 1fb88b9379668f51e89baba0d3873042c5ed1b9bf4489da33dd7b933b4174340

build:
  entry_points:
    - ghstack = ghstack.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - uv-build
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3,<4
    - click >=8,<9
    - requests >=2,<3
    - typing-extensions >=3
    - flake8 >=7,<8

test:
  imports:
    - ghstack
  commands:
    - pip check
    - ghstack --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ezyang/ghstack
  summary: Stack diff support for GitHub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
