{% set name = "ghstack" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ghstack-{{ version }}.tar.gz
  sha256: 000665fad2f42fcf51688abe60c332a271dbbd7d9a6e544d3063bc3c1626065e

build:
  entry_points:
    - ghstack = ghstack.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - aiohttp >=3,<4
    - click >=8,<9
    - requests >=2,<3
    - typing-extensions >=3,<5

test:
  imports:
    - ghstack
  commands:
    - pip check
    - ghstack --help
  requires:
    - pip

about:
  home: https://github.com/ezyang/ghstack
  summary: Stack diff support for GitHub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
