{% set name = "ghstack" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ghstack-{{ version }}.tar.gz
  sha256: 90a0c09ec8f463ef73939d1620448a9c4d723b3e9f887dc97f08be4b2163193f

build:
  entry_points:
    - ghstack = ghstack.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - aiohttp >=3,<4
    - click >=8,<9
    - requests >=2,<3
    - typing-extensions >=3,<5

test:
  imports:
    - ghstack
  commands:
    - pip check
    - ghstack --help
  requires:
    - pip

about:
  home: https://github.com/ezyang/ghstack
  summary: Stack diff support for GitHub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
